# Generated by Django 5.1.2 on 2024-10-31 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поста'),
        ),
    ]
