# Generated by Django 5.1.2 on 2024-10-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0002_alter_items_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', verbose_name='Фотография'),
        ),
    ]
