# Generated by Django 5.1.2 on 2024-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0003_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Фотография'),
        ),
    ]
