# Generated by Django 5.1.2 on 2024-11-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0005_category_image_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categ/', verbose_name='Фотография'),
        ),
    ]
